network:
  vpcID: vpc-0ed7419a484c71bf0
  subnets:
    - subnet-01e5a2c504271c633
    - subnet-042624b1683145840
    - subnet-05d12327efc80a3e8
applications:
  gifapi:
    image: 851725582403.dkr.ecr.us-east-1.amazonaws.com/gif-api:latest
  primechecker:
    image: 851725582403.dkr.ecr.us-east-1.amazonaws.com/prime-checker:latest      
  